/** @deprecated Import from `#app/utils/menu-catalog.server.ts` for new code. */
export {
	createMenuCategory,
	createMenuItem,
	createModifierGroup,
	createModifierOption,
	deleteMenuCategory,
	deleteMenuItem,
	deleteModifierGroup,
	deleteModifierOption,
	getMenuItem,
	getModifierGroup,
	listCategoriesForLocation,
	listItemsForLocation,
	listMenuForLocation,
	listModifierGroupsForLocation,
	menuCategorySchema,
	menuItemSchema,
	menuModifierGroupSchema,
	menuModifierOptionSchema,
	setMenuCategoryActive,
	setMenuItemActive,
	updateMenuCategory,
	updateMenuItem,
	updateModifierGroup,
	updateModifierOption,
} from '#app/utils/menu-catalog.server.ts'
